### ISSUE TITLE
[CompanyConceptRecord].Value displays inaccurate data

### ISSUE THREAD

**Issue by jsmithx** [kkartavenka/Sec.Edgar#1]
While testing out this project, I noticed that **Value** in object **CompanyConceptRecord** displays inaccurate data (i.e. decimal numbers were rounded to whole numbers).  After looking a bit into it, I noticed that **Value** is declared as a **long?** data type, which does not support decimals.  There are some data that require decimal numbers, like Earnings Per Share data, which should not be rounded to whole numbers to fit the **long?** data type.  Here is my suggestion on how we can fix this:

In the file "./Models/Edgar/CompanyConceptRecord.cs":
```
[JsonPropertyName("val"), JsonConverter(typeof(StringToNumericConverter<long>))]
public long? Value { get; init; }
```
should be changed to:
```
[JsonPropertyName("val"), JsonConverter(typeof(StringToNumericConverter<decimal>))]
public decimal? Value { get; init; }
```

Thank you for the tremendous amount of work in this project!

**Comment by kkartavenka** [comment]
Thank you @jsmithx. Resolved it as part of commit: https://github.com/kkartavenka/Sec.Edgar/commit/e864e39e8470a2e418aa1226f2897510a3936002. Feel free to download Nuget package 1.1.0
